#!/bin/bash

set -ux

source "env/common"

juju-log "Ensure Steam is up-to-date"
STEAM_EXIT=9000
while [ "$STEAM_EXIT" -ne 0 ]; do
	cd $INSTALL_USER_HOME/hlds/
	./steam
	STEAM_EXIT=$?
done

juju-log "Checking if game is installed"
if [ -e "$LOCAL_CFG_FILE" ]; then
	juju-log "Backing up configuration file."
	rm -f $INSTALL_USER_HOME/hlds/server/$GAME_CFG_DIR/sever.cfg.bak
	mv $INSTALL_USER_HOME/hlds/server/$GAME_CFG_DIR/server.cfg $INSTALL_USER_HOME/hlds/sever/$GAME_CFG_DIR/server.cfg.bak
else
	install_game
fi

update_configuration

chown -R steam.steam "$INSTALL_USER_HOME"
