#!/bin/bash
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

apt-get install -y apache2

egrep  -i "^steam" /etc/passwd
if [ $? -ne 0 ]; then
	adduser --disabled-password --disabled-login --gecos "Valve,Steam Server,,,," steam
fi

install_steam() {
	cd /home/steam && mkdir hlds && cd $_

	wget "http://storefront.steampowered.com/download/hldsupdatetool.bin"
	chmod +x hldsupdatetool.bin
	yes "yes" | ./hldsupdatetool.bin

	mkdir -p /home/steam/www/replays
}

cp opt/tf2-replays /etc/apache2/conf.d/
cp opt/tf2 /etc/init.d/ && chmod 0755 $_

chown -R steam.steam /home/steam

a2dissite default

mkdir -p /home/steam/hlds/server/orangebox/tf/cfg
cp opt/server.cfg /home/steam/hlds/server/orangebox/tf/cfg/

install_steam

open-port 80
open-port 27015
open-port 27016
