#!/bin/bash
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot

set -ux

source "env/common"

# HLDS NEVER gets updated. In fact it updates itself. This is the sha1 
#  of a verified working hldsupdatetool.bin
HLDS_SUM="3b8e0fcdd7375511f88556c3f8b698a28c93110f"

juju-log "Installing Apache"
apt-get install -y apache2

EGREP_PARAMS="^${INSTALL_USER}"
egrep  -i "$EGREP_PARAMS" /etc/passwd
if [ $? -ne 0 ]; then
	juju-log "Creating the Steam User"
	adduser --disabled-password --disabled-login --gecos "Valve,Steam Server,,,," "$INSTALL_USER"
fi

cp -f $CHARM_DIR/opt/$GAME-apache /etc/apache2/conf.d/
chown -R steam.steam $INSTALL_USER_HOME

a2dissite default

mkdir -p $INSTALL_USER_HOME/hlds/server/$INSTALL_USER_HOME
cp opt/$GAME.cfg $INSTALL_USER_HOME/hlds/server/$INSTALL_USER_HOME/server.cfg

juju-log "Installing the Steam Client"
install_steam
