#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

service apache2 restart

$INSTALL_USER_HOME/hlds/server/$GAME_BINARY -game $GAME_NAME -autoupdate -tickrate 66 +map cp_badlands -steambin /home/steam/hlds/steam &
