#!/bin/bash

CHARM_DIR=`pwd`
INSTALL_USER=`config-get system_user`
INSTALL_USER_HOME="/home/$INSTALL_USER"
GAME=`config-get game`
GAME_USES_APACHE=false

if [ -e "env/$GAME" ]; then
	source "env/$GAME"
else
	source "env/default"
fi
