#!/bin/bash

GAME_USES_APACHE=true
GAME_NAME="tf"
GAME_DIR="orangebox/tf"
GAME_CFG_DIR="$GAME_DIR/cfg"
GAME_BINARY="orangebox/srcds_linux"
LOCAL_CFG_FILE="/home/$INSTALL_USER/hlds/server/$GAME_CFG_DIR/server.cfg"

open-port 27015
open-port 27016
